### ISSUE TITLE
Concurrent map write fails

### ISSUE THREAD

**Issue by raviupreti85** [raviupreti85/database-design#1]
2017/12/02 10:02:02 Writing [key, value]
fatal error: concurrent map writes

goroutine 4918 [running]:
runtime.throw(0x456ceb, 0x15)
        /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:566 +0x95 fp=0xc4201bb5c0 sp=0xc4201bb5a0
runtime.mapassign1(0x3d2ec0, 0xc420173500, 0xc4201bb778, 0xc4201bb710)
        /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/hashmap.go:458 +0x8ef fp=0xc4201bb6a8 sp=0xc4201bb5c0

**Comment by raviupreti85** [comment]
Fixed by PR1
